Development
peterrobert/Building-with-Backgrounds-and-Gradients pull request #1
Opened 2020-01-23 13:30 UTC by peterrobert

project ready for review

2020-01-24 00:09 UTC, rOluochKe requested changes
@peterrobert 
### This is impressive, good job so far, however, there are few changes you need to make for the project to be approved
- Write a more descriptive pull request showing what you have done on the project [check this guide for more info](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- write a more detailed readme file explaining what the project is all about, technologies, license, contributors, who I can install the project [check this guide](https://github.com/microverseinc/readme-template)
- Make sure your project passes linting both HTML and CSS [check this guide](https://github.com/microverseinc/linters-config/tree/master/css)
- Your navigation is still off from the original design, no logo, the gradient is still off and the search 
![navigation](https://user-images.githubusercontent.com/8114528/73034684-a7b52e80-3e56-11ea-9f4d-153b8629a54e.PNG)

- Always remember you can ask for help from slack, your team, mentor and or any TSE
### Once you make all these changes, resubmit your project for a review. I wish you all the best

2020-01-24 08:30 UTC, peterrobert commented
**Building-with-Backgrounds-and-Gradients Milestone 1: Complete Project**

In this milestone, I have completed the following:

- Created and validated the HTML mark up.

- Created and validated the CSS mark up.

- Added font-awesome and used some of its elements on my mark up

- Added stickler in order to fix common CSS issues

2020-01-25 08:31 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE) 

### Hello @peterrobert  :bulb: 
### I'm really impressed by the good work you've done so far :clap: thank you for making the changes the previous TSE requested, there are still a couple of mandatory requirements left before we can give you the approval:

- [ ]  The text in your footer shouldn't be bold

 **General**

- [ ] Comments: It’s better to delete commented code

[OPTIONAL] your navbar grid is darker than the original maybe you could play with some different combinations to achieve a more similar look (I have left an example in the commented code for you to try.)

#### I have commented on the lines of code that need to be fixed but its been a blast to review this project. :clinking_glasses:

### Please :pray: correct these changes and submit back for a code review when you are done :rocket:

#### Happy Coding! :woman_technologist:

STATUS OF THE PROJECT: REQUESTED CHANGES :traffic_light:

2020-01-25 08:31 UTC, euqueme commented on index.html
> +    <!-- ====fonts ==== -->
Delete commented code

2020-01-25 08:31 UTC, euqueme commented on index.html
>      <!-- === links === -->
**Delete commented code**

2020-01-25 08:31 UTC, euqueme commented on index.html
> -    <!-- ==== font awesome cdn ===== -->
Delete commented code

2020-01-25 08:31 UTC, euqueme commented on index.html
> +    <!-- ===== footer section === -->
Delete commented code

2020-01-25 08:31 UTC, euqueme commented on style.css
> +  background-image: linear-gradient(#333, #5c5c5c);
[Optional] try this gradient instead
background-image: linear-gradient(#9c9c9c 20%,#5c5c5c, #4c4c4c);

2020-01-25 08:31 UTC, euqueme commented on index.html
> +                <h5>Copyright © 2014 Apple Inc. All rights reserved. Terms of UsePrivacy Policy</h5>
The font-weight of these lines should be less than 500

2020-01-25 09:23 UTC, peterrobert commented
All changes have been done as asked.

2020-01-25 16:41 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE) :woman_technologist:

### Hii @peterrobert :handshake: 

I downloaded your project and I notice you made all the changes :raised_hands:   but the Live Demo doesn't reflect them :thinking: 
![image](https://user-images.githubusercontent.com/52209067/73124218-70ca4000-3f5e-11ea-9fe7-0987a9ec7a27.png)

### Please correct this :memo:  and submit the project right away no need to ask for a code review anymore

STATUS OF THE PROJECT: APPROVED :green_apple:

2020-01-27 14:30 UTC, merged